version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: sandaru71/velociroute-backend:latest
    container_name: velociroute-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - velociroute-network
    volumes:
      - ./uploads:/usr/src/app/uploads

networks:
  velociroute-network:
    driver: bridge
