version: "3.8"

services:
  ml-service:
    image: sandaru71/velociroute-ml-service:latest
    container_name: velociroute-ml-service
    ports:
      - "8000:8000"
    environment:
      - MODEL_DEVICE=cpu
      - BATCH_SIZE=1
      - HOST=0.0.0.0
      - PORT=8000
    restart: unless-stopped
    networks:
      - velociroute-network

networks:
  velociroute-network:
    external: true
