version: '3.8'

services:
  ml-service:
    image: sandaru71/velociroute-ml-service:latest
    container_name: velociroute-ml-service
    ports:
      - "8000:8000"
    environment:
      - MODEL_DEVICE=cpu
      - BATCH_SIZE=1
      - HOST=0.0.0.0
      - PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
