version: '3.8'

services:
  backend:
    image: sandaru71/velociroute-backend:latest
    container_name: velociroute-backend
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - ../uploads:/usr/src/app/uploads

  ml-service:
    image: sandaru71/velociroute-ml:latest
    container_name: velociroute-ml
    ports:
      - "5000:5000"
    environment:
      - MODEL_DEVICE=cpu
      - BATCH_SIZE=4
      - HOST=0.0.0.0
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
